<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>
<div class="about-area pt-80 pb-80">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-xl-12 col-lg-12">
                <div class="about-content">
                    <p>By using this website and/or placing an order, you agree to be bound by the terms and conditions set out below. Please also read our Privacy Policy regarding personal information provided by you.</p>
                    <p>No prior notice for amendment to the terms, the amendment will be applied to orders thereafter. Upon confirmation of your orders, we will not be able to make any changes.</p>
                    <p>1. TERMS AND CONDITIONS TO GOVERN &ndash; These terms and conditions represent the final and complete agreement of the parties and no terms or conditions in anyway modifying or changing the provisions stated herein shall be binding upon Our Company unless made in writing and signed and approved by an officer or other authorized person at Our Company. No modification of any of these terms shall be modified by Our Company&rsquo;s shipment of goods following receipt of Buyers purchase order, shipping request or similar forms containing printed terms and conditions additional to or in conflict with the terms herein. If any term, clause or provision is declared to held invalid by a court of competent jurisdiction, such declaration or holding shall not affect the validity of any other term, clause or provision here in contained.</p>
                    <p>2. ACCEPTANCE OF ORDERS &ndash; All orders are subject to written price verification by authorized Our Company personnel unless designated in writing to be firm for a specified period of time. Shipment of goods without written price verification does not constitute acceptance of the price contained in the order.</p>
                    <p>3. SUBSTITUTION &ndash; Our Company reserves the right, without prior notification, to substitute an alternative product of like kind, quality and function. If the Buyer will not accept a substitute, the Buyer must specifically declare that no substitution is allowed when the buyer requests a quote, if such request for quote is made, or, if no request for quote was made ,when placing an order with the Our Company.</p>
                    <p>4. PRICE &ndash; Prices quoted, including any transportation charges, are valid for 10 days unless designated as firm for as pacific period pursuant to a written quote or written sales acceptance is sued or verified by an officer or other authorized personnel of Our Company. A price designated as firm for a specific period may be revoked by Our Company if the revocation is in writing and is mailed to the Buyer prior to the time a written acceptance of the price is received by Our Company. All prices and deliveries are F.O.B. shipping point. Our Company reserves the right to cancel orders in the event selling prices which are lower than prices quoted are established by government regulations.</p>
                    <p>5. TRANSPORTATION &ndash; Unless otherwise provided, Our Company shall use it judgment in determining carrier and routing. In either case, Our Company shall not be liable for any delays or excessive transportation charges resulting from its selection.</p>
                    <p>6. PACKING &ndash; Unless otherwise provided, Our Company will comply only with it is minimum packing standards for the method of transportation selected. The cost of all special packing, loading or bracing requested by Buyer will be paid for by Buyer. All cost of packing and shipment for Buyer&rsquo;s special equipment shall be paid for by Buyer.</p>
                    <p>7. PAYMENT TERMS &ndash; The discount applies only to the invoiced value of the material (not to taxes or freight charges). Our Company reserves the right to require advance payment or satisfactory security for the goods if the financial condition of Buyer so warrants as determined by Our Company. If Buyer fails to make payment in accordance with terms of this agreement or any collateral agreement, or fails to comply with any provisions hereof, Our Company may, at its option (and in addition to other remedies), cancel any unshipped portion of this order. Buyer is to remain liable for all unpaid accounts.</p>
                    <p>8. TAXES AND IMPORT/EXPORT LICENSES &ndash; Prices do not include taxes. Taxes are paid by Buyer upon invoice from Our Company unless Buyer provides a valid exemption certificate acceptable to the taxing authority or unless Our Company&rsquo;s forbidden by law from collection of said taxes from Buyer. Import or export licenses are to be secured by Buyer.</p>
                    <p>9. TITLE AND RISK OF LOSS &ndash; Delivery to carrier shall constitute delivery to Buyer, and thereafter risk of loss or damage shall pass to Buyer. Any claim of Buyer relative to damage during shipping or delivery should be made directly to the carrier. Any claims by Buyer against Our Company for shortage or damage occurring prior to such delivery to carrier must be made within five (5) days after receipt of the goods and accompanied by original transportation bill signed by carrier noting that carrier received the goods from Our Company in the condition claimed. Not with standing passage of the risk of loss to Buyer, title and right of possession to the goods sold hereunder shall remain with Our Company until all payments hereunder, including deterred payments evidenced by notes or other wise, Interest, carrying charges, and attorneys&rsquo; fees, shall have been made in cash, and Buyer agrees to do all acts necessary to perfect and maintain such right and title in Our Company.</p>
                    <p>10. RETURN OF PRODUCTS &ndash; Goods cannot be returned, and orders once accepted by Our Company cannot be cancelled, except upon the written approval of Our Company. Cut to size items and special orders may not be returned unless it has been determined to be provided in error by Our Company. Customers returning goods are responsible for freight charges, and shall be assessed a restocking fee of 100 or 20% of the order, whichever is greater.</p>
                    <p>11. FORCE MAJEURE &ndash; Our Company shall not be liable for failure to perform its obligations resulting directly or indirectly from or contributed to by acts of God; acts of Buyer, civil or military authority, including wage and price controls; fires; war; riot; delays in transportation; lack of or inability too brain raw materials (including energy sources), components, labor, fuel or supplies; or other circumstances beyond Our Company&rsquo;s reasonable control, whether similar or dissimilar to the foregoing. If certain quantities are affected and other quantities are not, the quantities affected shall be eliminated without liability, but the agreement shall remain unaffected. Our Company may during any period of shortage due to any of saidcauses, allocate its supply of such raw materials among its various users thereof in any manner which we deems fair and reasonable. In no event shall Our Company be liable for special or consequential damages for any delay for any cause.</p>
                    <p>12. REASONABLE ATTORNEY&rsquo;S FEES &ndash; In the event suit or other proceedings shall be brought for the recovery of the purchase price, or any unpaid balance, or the breach by Buyer of any term here in contained, Buyer shall&hellip;</p>
                </div>
            </div>
        </div>
    </div>
</div>